steps:
# 1. Build Application Image
- id: 'build-image'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest'
    - '-t'
    - '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:__COMMIT_SHA__'
    - '.'

# 2. Push tags
- id: 'push-latest'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:latest'

- id: 'push-sha'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:__COMMIT_SHA__'

# 3. Update Manifests 
- name: 'ubuntu'
  id: 'update-manifests'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      mkdir -p k8s
      # Substitute the latest commit SHA into the deployment template
      sed "s|__IMAGE_TAG_PLACEHOLDER__|__COMMIT_SHA__|g" templates/deployment.yaml > k8s/deployment.yaml
      
      # Substitute other variables into service and ingress (no SHA needed)
      envsubst < templates/service.yaml > k8s/service.yaml
      envsubst < templates/ingress.yaml > k8s/ingress.yaml
  waitFor: ['push-sha']
  
# 4. Database Migration (Runs the provided migrate.sh script inside the built container)
- name: '$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:__COMMIT_SHA__'
  id: 'migrate-db'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      # The migrate.sh script is located at /app/migrate.sh inside the container image.
      chmod +x /app/migrate.sh
      /app/migrate.sh
  env:
    # This environment variable is required by migrate.sh for the proxy connection.
    - 'INSTANCE_CONNECTION_NAME=__INSTANCE_CONNECTION_NAME__' 
  # Load ALL sensitive data from Secret Manager via the availableSecrets array below.
  secretEnv: ['DB_PASS', 'DB_USER', 'DB_NAME']
  waitFor: ['push-sha'] 

# 5. Get GKE Credentials
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'gke-auth'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - '$CLUSTER_NAME'
    - '--zone'
    - '$ZONE'
    - '--project'
    - '$PROJECT_ID'
  waitFor: ['migrate-db', 'update-manifests']

# 6. Deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'kubectl-apply'
  args:
    - 'apply'
    - '-f'
    - 'k8s/'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=$ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$CLUSTER_NAME'
  waitFor: ['gke-auth']

# Global variables for substitution in Cloud Build steps
substitutions:
  _COMMIT_SHA: 'latest' # Default commit SHA will be provided by Cloud Build trigger

# Secrets used by the Migration step
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sql-password/versions/latest
    env: 'DB_PASS'
  - versionName: projects/$PROJECT_ID/secrets/sql-user/versions/latest
    env: 'DB_USER'
  - versionName: projects/$PROJECT_ID/secrets/sql-db/versions/latest
    env: 'DB_NAME'

# Cloud Build configuration options
options:
  logging: CLOUD_LOGGING_ONLY